[package]
name = "hue"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
log = "0.4.22"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde_json = "1.0.128"
